CREATE DATABASE christian;

CREATE TABLE cliente(
DNICli VARCHAR(10) NOT NULL,
NomCli VARCHAR(25) NOT NULL,
Ap1Cli VARCHAR(15) NULL,
Ap2Cli VARCHAR(15) NULL,
CalleCli VARCHAR(30) NULL,
NumCli INT NULL,
CPCli INT NOT NULL,
TelCli INT(10) NULL,
PRIMARY KEY(DNICli),
FOREIGN KEY(CPCli) REFERENCES provincias(cp)
);

CREATE TABLE comercio(
CIFCom VARCHAR(10) NOT NULL,
NomCom VARCHAR(25) NOT NULL,
CalleCom VARCHAR(30) NULL,
NumCom INT NULL,
CPCom INT NOT NULL,
TelCom INT(10) NULL,
PRIMARY KEY(CIFCom),
FOREIGN KEY(CPCom) REFERENCES provincias(cp)
);

CREATE TABLE programa(
CodProg INT AUTO_INCREMENT NOT NULL,
NomProg VARCHAR(30) NOT NULL,
VerProg FLOAT NOT NULL,
CodFab INT AUTO_INCREMENT NOT NULL,
PRIMARY KEY(CodProg),
FOREIGN KEY(CodFab) REFERENCES fabricante(CodFab)
);

CREATE TABLE fabricante(
CodFab INT AUTO_INCREMENT NOT NULL,
Nombre VARCHAR(30) NOT NULL,
Pais VARCHAR(15),
PRIMARY KEY(CodFab)
);

CREATE TABLE distribuir(
CodDistr INT AUTO_INCREMENT NOT NULL,
CodProg INT AUTO_INCREMENT NOT NULL,
CIFCom VARCHAR(10) NOT NULL,
Cant INT NULL,
PRIMARY KEY(CodDistr),
FOREIGN KEY(CodProg) REFERENCES programa(CodProg),
FOREIGN KEY(CIFCom) REFERENCES comercio(CIFCom)
);

CREATE TABLE compra(
CodCompra INT AUTO_INCREMENT NOT NULL,
CodProg INT AUTO_INCREMENT NOT NULL,
CIFCom VARCHAR(10) NOT NULL,
DNICli VARCHAR(10) NOT NULL,
FormaP VARCHAR(10) NOT NULL,
PRIMARY KEY(CodCompra),
FOREIGN KEY(CodProg) REFERENCES programa(CodProg),
FOREIGN KEY(CIFCom) REFERENCES comercio(CIFCom),
FOREIGN KEY(DNICli) REFERENCES cliente(DNICli)
);

CREATE TABLE provincias(
CP INT NOT NULL,
Provincia VARCHAR(10) NOT NULL,
PRIMARY KEY(CP)
);